try:
    print('try')
except:
    print('except')
try:
    print('try')
finally:
    print('finally')

# This is valid
# output:
# try
# try
# finally


